name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Set up GolangCI-Lint
      run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- v1.17.1

    - name: Test
      env:
        GO111MODULE: on
      run: go test -v ./...

    - name: Lint
      env:
        GO111MODULE: on
      run: ./bin/golangci-lint -E gocritic -E misspell -E gocyclo -E golint -E gosec run ./...
